    float3x3 baseColorTexcoordTransform;
    float3x3 emissiveTexcoordTransform;
    float3x3 roughnessTexcoordTransform;
    float3x3 metallicTexcoordTransform;
    float3x3 specularTexcoordTransform;
    float3x3 normalTexcoordTransform;
    float3x3 ambientOcclusionTexcoordTransform;
    float3x3 reflectionTexcoordTransform;
    float3x3 irradianceTexcoordTransform;
