#!/bin/bash

rm -rf build

xcodebuild archive \
    -project Satin.xcodeproj \
    -scheme Satin \
    -configuration Release \
    -archivePath "build/iOS" \
    -destination 'generic/platform=iOS' \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild archive \
    -project Satin.xcodeproj \
    -scheme Satin \
    -configuration Release \
    -archivePath "build/iOS_Simulator" \
    -destination 'generic/platform=iOS Simulator' \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild archive \
    -project Satin.xcodeproj \
    -scheme Satin \
    -configuration Release \
    -archivePath "build/macOS" \
    -destination 'generic/platform=macOS' \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild archive \
    -project Satin.xcodeproj \
    -scheme Satin \
    -configuration Release \
    -archivePath "build/visionOS" \
    -destination 'generic/platform=visionOS' \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild archive \
    -project Satin.xcodeproj \
    -scheme Satin \
    -configuration Release \
    -archivePath "build/visionOS_Simulator" \
    -destination 'generic/platform=visionOS Simulator' \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild -create-xcframework \
    -framework build/iOS.xcarchive/Products/Library/Frameworks/Satin.framework \
    -framework build/iOS_Simulator.xcarchive/Products/Library/Frameworks/Satin.framework \
    -framework build/macOS.xcarchive/Products/Library/Frameworks/Satin.framework \
    -framework build/visionOS.xcarchive/Products/Library/Frameworks/Satin.framework \
    -framework build/visionOS_Simulator.xcarchive/Products/Library/Frameworks/Satin.framework \
    -output build/Satin.xcframework