#!/bin/bash

rm -rf build
xcodebuild archive -project Satin.xcodeproj -scheme Satin -configuration Release -archivePath build/ios -destination 'generic/platform=iOS' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive -project Satin.xcodeproj -scheme Satin -configuration Release -archivePath build/ios_sim -destination 'generic/platform=iOS Simulator' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive -project Satin.xcodeproj -scheme Satin -configuration Release -archivePath build/macos -destination 'generic/platform=macOS' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive -project Satin.xcodeproj -scheme Satin -configuration Release -archivePath build/visionos -destination 'generic/platform=visionOS' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive -project Satin.xcodeproj -scheme Satin -configuration Release -archivePath build/visionos_sim -destination 'generic/platform=visionOS Simulator' SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild -create-xcframework \
    -framework build/ios.xcarchive/Products/Library/Frameworks/Satin.framework \
    -framework build/ios_sim.xcarchive/Products/Library/Frameworks/Satin.framework \
    -framework build/macos.xcarchive/Products/Library/Frameworks/Satin.framework \
    -framework build/visionos.xcarchive/Products/Library/Frameworks/Satin.framework \
    -framework build/visionos_sim.xcarchive/Products/Library/Frameworks/Satin.framework \
    -output build/Satin.xcframework